name: main

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: up stack
        run: docker-compose up -d
      - name: run tests
        run: docker-compose run --entrypoint pytest -p no:cacheprovider
